spring.application.name=utencilio

spring.datasource.url=jdbc:postgresql://crossover.proxy.rlwy.net:55360/railway
spring.datasource.username=postgres
spring.datasource.password=srWHixDIuirwgNMqTBgTQbecnIbzFVbf

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jps.properties.hibernate.dialect= org.hibernate.dialect.PostgreSqlDialect